### ISSUE TITLE
[ML] Error during classification analytics

### ISSUE THREAD

**Issue by pheyos** [elastic/ml-cpp#1040]
**Found in version**
- 8.0.0 - starting with mini stack build 6683, where https://github.com/elastic/elasticsearch/pull/53108 went in

**Steps to reproduce**
- Create and start a classification job based in the bank-marketing dataset
- Configuration:
```
{
  "description": "",
  "source": {
    "index": "bank-marketing*"
  },
  "dest": {
    "index": "dest-bm_1"
  },
  "analyzed_fields": {
    "excludes": []
  },
  "analysis": {
    "classification": {
      "dependent_variable": "y",
      "training_percent": "20"
    }
  },
  "model_memory_limit": "200mb"
}
```

**Expected result**
- The classification job finishes without errors

**Actual result**
- The job goes into `failed` state with the following error in the job messages:
```
Updated analytics task state to [failed] with reason [[bm_1_1583497643615] analytics process stopped unexpectedly: Fatal error: 'si_signo 11, si_code: 1, si_errno: 0, address: 0x7ff15024cc91, library: /home/robert/github/machine-learning-qa/build/deployments/8.0.0/6683/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/../lib/libMlMaths.so, base: 0x7ff150015000, normalized address: 0x237c91', version: 8.0.0-SNAPSHOT (build 9abec24aff83ac) ]
```

**Additional information**
- When running a classification job with different input data, e.g. Kibana sample flight data, the job runs without errors, so it's probably input data related.

**Comment by droberts195** [comment]
There was a syslog message:

```
Updated analytics task state to [failed] with reason [[bm_1_1583489004749] analytics process stopped unexpectedly:
Fatal error: 'si_signo 11, si_code: 1, si_errno: 0, address: 0x7f8968223941, library: /home/robert/github/machine-learning-qa/build/deployments/8.0.0/6687/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/../lib/libMlMaths.so, base: 0x7f8967feb000, normalized address: 0x238941', version: 8.0.0-SNAPSHOT (build 0108a6ecf8a983) ]
```

Looking up the function from that shows the crash happened in `_ZN2ml5maths15CDataFrameUtils19metricMicWithColumnERKNS1_12CColumnValueERKNS_4core10CDataFrameERKNS5_16CPackedBitVectorESt6vectorImSaImEE`, which demangles to `ml::maths::CDataFrameUtils::metricMicWithColumn(ml::maths::CDataFrameUtils::CColumnValue const&, ml::core::CDataFrame const&, ml::core::CPackedBitVector const&, std::vector<unsigned long, std::allocator<unsigned long> >)`.
