### ISSUE TITLE
[ML] Start reporting analytics stats earlier

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/ml-cpp#1105]
At the moment, memory usage and analysis stats start being reported quite some time into running an analysis. This leaves users uninformed for what may be a long time. Could we start reporting them earlier? For example, memory usage may be reported the moment we start the analysis as `0` and then report it as soon as data is loaded into the data frame.

**Comment by valeriy42** [comment]
I created a [dedicated issue for the memory reporting](#1282).

@dimitris-athanasiou do you think we can close this issue to avoid duplication?

**Comment by dimitris-athanasiou** [comment]
I think you meant to link this issue https://github.com/elastic/ml-cpp/issues/1282 ?

Could we also report the stats earlier? If yes, then we should also raise an issue for that. If not, I'm happy to close this one.

**Comment by valeriy42** [comment]
Yes, I meant #1282 . This one is reporting `memory_stats`. For other stats, e.g. `regression_stats`, we would need a completely different format in the initialization phase. We also didn't discuss any use case where this information would be required.

**Comment by dimitris-athanasiou** [comment]
OK, makes sense. Closing this one.
