### ISSUE TITLE
[ML] Continue supervised learing job from a checkpoint

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#1281]
After a failure (e.g. after running out of memory) or an early stopping I don't want to loose all data (in particular the valid intervals for the hyperparameter search and the GP for hyperparameter optimization). Therefore I want to be able to continue training from a given checkpoint.

This functionality is already partially implemented in the persist/restore functionality. What changes is that now I want to modify the job configuration, e.g. by giving a job more memory or by increasing the number of hyperparameter optimization steps.

**Comment by tveasey** [comment]
This is now implemented. See for example, #1298, #1300, etc.
