### ISSUE TITLE
[ML] Option to use NDJSON for CJsonOutputStreamWrapper

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#1329]
A better option might be to add an optional argument to the `CJsonOutputStreamWrapper` constructor to say whether to output JSON or ND-JSON.

About 6-7 years ago JSON purists were in the ascendency and ND-JSON was considered impure.  So we got into the situation where our programs output multi-gigabyte JSON arrays just so that their entire output is a valid JSON document.  On the receiving side this has to be parsed using a stream parser rather than waiting for a complete JSON document, so the array structure is completely pointless.

Now ND-JSON is considered the sane way to deal with a stream of JSON documents, so we should use it for new types of output.

It isn't very hard to change `CJsonOutputStreamWrapper` to do this. In ND-JSON mode it would:

- Never write `JSON_ARRAY_START`
- Never write `JSON_ARRAY_END`
- Never write `JSON_ARRAY_DELIMITER` (there are already newlines between the documents as well as commas)

Then you don't need the inefficient string manipulation at the end of this method, and there's a side benefit that one of our core classes encourages the more modern approach for the future.

_Originally posted by @droberts195 in https://github.com/elastic/ml-cpp/pull/1316_

**Comment by droberts195** [comment]
Maybe this isn't necessary after all.  If my suggestion of https://github.com/elastic/ml-cpp/pull/1349/files#r446114347 is viable then the code that would take advantage of this change will be writing to a simple `ostream` instead.

**Comment by valeriy42** [comment]
Indeed this becomes unnecessary with #1371. Hence, I am closing this issue.
