### ISSUE TITLE
[ML] Avoid instantiating string for writing model definition

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#1364]
As discussed [here](https://github.com/elastic/ml-cpp/pull/1349#pullrequestreview-438128635)  inference model definition code should be refactored to avoid creating a string and load it into main memory. We should use the filtering mechanism and enhance it with chunking the definition in a streaming fashion.

Implementation of #1329 is a technical requirement for this issue.

**Comment by droberts195** [comment]
> Implementation of #1329 is a technical requirement for this issue.

That might not be true.

I mentioned in https://github.com/elastic/ml-cpp/pull/1349#discussion_r446114347 that it might not be necessary to construct RapidJSON objects as an intermediate step of the conversion from our objects to JSON text.

For example, suppose you changed this:

```
void CTargetMeanEncoding::addToDocument(rapidjson::Value& parentObject,
                                        TRapidJsonWriter& writer) const {
    this->CEncoding::addToDocument(parentObject, writer);
    writer.addMember(JSON_DEFAULT_VALUE_TAG,
                     rapidjson::Value(m_DefaultValue).Move(), parentObject);
    writer.addMember(JSON_FEATURE_NAME_TAG, m_FeatureName, parentObject);

    rapidjson::Value map{writer.makeObject()};
    for (const auto& mapping : m_TargetMap) {
        writer.addMember(mapping.first, rapidjson::Value(mapping.second).Move(), map);
    }
    writer.addMember(JSON_TARGET_MAP_TAG, map, parentObject);
}
```

to this:

```
using TGenericLineWriter = core::CRapidJsonLineWriter<rapidjson::OStreamWrapper>;

void CTargetMeanEncoding::addToJsonStream(TGenericLineWriter& writer) const {
    this->CEncoding::addToJsonStream(writer);
    writer.Key(JSON_DEFAULT_VALUE_TAG);
    writer.Double(m_DefaultValue);
    writer.Key(JSON_FEATURE_NAME_TAG);
    writer.String(m_FeatureName);

    writer.Key(JSON_TARGET_MAP_TAG);
    writer.StartObject();
    for (const auto& mapping : m_TargetMap) {
        writer.Key(mapping.first);
        writer.Double(mapping.second);
    }
    writer.EndObject();
}
```

This is writing to the `ostream` in a non-thread-safe way: if multiple threads were writing to that same `ostream` then the output would be hopelessly mixed up.  However, this `ostream` _won't_ be the final process output, but instead the compression stream that will eventually get put into strings in an outer JSON document that _will_ be written to the process output in a thread-safe way.

Obviously you'd need to change the whole hierarchy of methods that build the inference model definition to be like this.  But there would be other benefits.  At the moment I think we are holding the model in 4 uncompressed forms simultaneously at one point:

1. Our internal data structures
2. The RapidJSON data structures
3. The JSON string surrounded by `[` and `]`
4. The JSON string with `[` and `]` stripped

While it's worthwhile to remove 3, we can also benefit from removing 2 by converting directly from our data structures to JSON text in the way I outlined above.  And then by having that text go directly to the compression stream we also remove 4 and end up with:

1. Our internal data structures
2. The compressed JSON string

(plus a few intermediate buffers required by the compressor that will not vary in size depending on the model size)

**Comment by valeriy42** [comment]
Thank you for your idea @droberts195 . At the moment, we are using `CRapidJsonConcurrentLineWriter` in `CDataFrameAnalyzer::run()` in the following manner:
```c++
...
core::CRapidJsonConcurrentLineWriter outputWriter{*outStream};
CDataFrameAnalysisInstrumentation::monitor(instrumentation, outputWriter);
 ...
this->writeResultsOf(*analysisRunner, outputWriter);
```

This mean, I will need to hijack `outStream` to write the compressed model directly, right?

**Comment by droberts195** [comment]
> This mean, I will need to hijack `outStream` to write the compressed model directly, right?

No, you can still write the compressed model to the overall process output stream using the same thread-safe mechanism.

What I meant was that the uncompressed version can be written directly into the compression stream, which is a local variable so there's no danger of multiple threads writing to it at the same time.

At the moment you have this method:

```
std::stringstream CInferenceModelDefinition::jsonStringCompressedFormat() const {
    std::stringstream compressedStream;
    using TFilteredOutput = boost::iostreams::filtering_stream<boost::iostreams::output>;
    std::string modelDefinitionStr{jsonString()};
    {
        TFilteredOutput outFilter;
        outFilter.push(boost::iostreams::gzip_compressor());
        outFilter.push(core::CBase64Encoder());
        outFilter.push(compressedStream);
        outFilter << modelDefinitionStr;
        outFilter.flush();
    }
    return compressedStream;
}
```

In that `TFilteredOutput` is a `std::ostream`.  So if you change the `addToDocument` methods as I suggested then I think you can change it to something like this:

```
using TGenericLineWriter = core::CRapidJsonLineWriter<rapidjson::OStreamWrapper>;

std::stringstream CInferenceModelDefinition::jsonStringCompressedFormat() const {
    std::stringstream compressedStream;
    using TFilteredOutput = boost::iostreams::filtering_stream<boost::iostreams::output>;
    {
        TFilteredOutput outFilter;
        outFilter.push(boost::iostreams::gzip_compressor());
        outFilter.push(core::CBase64Encoder());
        outFilter.push(compressedStream);

        TGenericLineWriter writer{outFilter};
        this->addToJsonStream(writer);
    }
    return compressedStream;
}
```

So the idea is that the hierarchy of `addToJsonStream` methods will directly write into the `ostream` that is `TFilteredOutput` via the `TGenericLineWriter`.  As the text gets written it will be compressed and the compressed version will build up in `compressedStream`.  The uncompressed text won't build up anywhere - as soon as `outFilter` has enough to compress in its internal buffer it will compress it and discard the buffer.

Then the `compressedStream` contents can be handled as they currently are.  The overall process output will remain thread-safe.

I may have got the code slightly wrong in this comment, but hopefully you can see the idea.  _Something_ along these lines will work.
