### ISSUE TITLE
[ML] Peak memory usage should be adjusted before reporting

### ISSUE THREAD

**Issue by droberts195** [elastic/ml-cpp#1478]
In #1389 we added peak memory usage to the model size stats.  However, the value reported for peak memory usage is the true measured value whereas the value reported for current memory usage is adjusted, hence the two values are not commensurate.  At the point where the job is using its peak memory usage it is likely we report peak memory usage as half of current memory usage, due to the way we double the current memory usage when background persistence is in operation.  (There is another adjustment too, but not as big.)

This should be fixed by introducing a new "adjusted peak usage" statistic in the same way we have "adjusted usage".  So where we have:

```
    res.s_Usage = this->totalMemory();
    res.s_AdjustedUsage = this->adjustedUsage(res.s_Usage);
    res.s_PeakUsage = static_cast<std::size_t>(
        core::CProgramCounters::counter(counter_t::E_TSADPeakMemoryUsage));
```

in `CResourceMonitor` we should add:

```
    res.s_AdjustedPeakUsage = this->adjustedUsage(res.s_PeakUsage);
```

Then `CModelSizeStatsJsonWriter::write` should output `s_AdjustedPeakUsage` in place of `s_PeakUsage`.  (Note that `s_Usage` is not reported to the outside world in this method.)

Once this is done it should be possible to add a Java integration test that asserts that peak memory usage is greater than or equal to current memory usage.

**Comment by przemekwitek** [comment]
FYI: I've just started working on this issue.
