### ISSUE TITLE
Forecast bounds are too thin

### ISSUE THREAD

**Issue by pheyos** [elastic/ml-cpp#1606]
**Found in version**
- 7.10.1-bc2

**Steps to reproduce**
- Run a forecast for an anomaly detection job.

**Expected result**
- Predicted value and forecast bounds are sensible.

**Actual result**
- The forecast bounds are super "thin":

![farequote_forecast_7 10 0_vs_7 10 1](https://user-images.githubusercontent.com/1945390/101152761-d0d04f00-3623-11eb-8e36-df648cab8891.png)
![image](https://user-images.githubusercontent.com/1945390/101152782-d75ec680-3623-11eb-9aab-55ea5f8b156c.png)

**Additional information**
- This is a regression, in 7.10.0 the forecast bounds are looking good.

**Comment by droberts195** [comment]
This was caused by https://github.com/elastic/ml-cpp/pull/1559, which was supposed to just be a test fix for the problem of many elasticsearch-ci workers having very little disk space.  But it has also had this side effect.  For the 7.10 branch I will just revert the commits.

**Comment by droberts195** [comment]
The commits related to forecasting have been reverted from 7.10.  I'll work on a proper fix for 7.x and master.
