### ISSUE TITLE
[ML] Early stopping for hyperparameter optimization procedure

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#1669]
There are several scenarios when hyperparameter optimization doesn't seem to work. When the CV loss variation is too high, model performance basically varies from the fold to fold so much that the algorithm scales the whole GP down to a constant (\theta_0 -> 0), In this case, we can interrupt the `fine_parameter_tuning` phase without a problem, since any potential improvement is due to randomness and not due to a particular choice of the parameters.

To this end, in order to introduce early stopping, in `selectNextHyperparameters()` one can check after the random sampling phase if the 0-s element of `m_KernelParameters` is very small (e.g.  1e-9) or alternatively if the total variation of the GP is very small. Then the method should return `false` and the `fine_parameter_tuning` phase will be interrupted as intended.

**Comment by valeriy42** [comment]
WDYT @tveasey?

**Comment by tveasey** [comment]
This sounds correct to me, i.e. maximum likelihood should be choosing a constant process if the variation across the set of values sampled values is small compared to the accuracy with which they can be measured. In this case there is no reason to expect we'll get lucky by trying more values and fall across a much better solution.
