### ISSUE TITLE
[CI] Failures of CDataFrameAnalyzerFeatureImportanceTest.testRegressionFeatureImportanceNoImportance

### ISSUE THREAD

**Issue by droberts195** [elastic/ml-cpp#1693]
Very occasionally CI builds are failing in the `CDataFrameAnalyzerFeatureImportanceTest.testRegressionFeatureImportanceNoImportance` test with this assertion failure:

```
[Exception] - difference{0.103158} between c1{100.57140843449896} and prediction{91.166793823242202} exceeds 8%
 == [File] - CDataFrameAnalyzerFeatureImportanceTest.cc
 == [Line] -621
```

This happened on one native macOS CI build on the 7.x branch, and on one native macOS CI build with assertions enabled on the master branch.

The intermittent failures suggest that this test is either susceptible to race conditions or is susceptible to running on a machine with less memory than most test machines have.

**Comment by droberts195** [comment]
This is now consistently failing in this way in the native macOS CI build with assertions enabled on the master branch:

<img width="848" alt="Screenshot 2021-01-28 at 10 10 26" src="https://user-images.githubusercontent.com/7405510/106122862-1b1c0b00-6151-11eb-802d-5fed9ef279fb.png">

The error is always the same:

```
[Exception] - difference{0.103158} between c1{100.57140843449896} and prediction{91.166793823242202} exceeds 8%
 == [File] - CDataFrameAnalyzerFeatureImportanceTest.cc
 == [Line] -621
```

So it looks like one of the commits on 21st January made this test non-deterministic:

<img width="1254" alt="Screenshot 2021-01-28 at 10 12 05" src="https://user-images.githubusercontent.com/7405510/106123063-5e767980-6151-11eb-9914-5c4b1a70ad0a.png">

And since the numbers in the failure message are always exactly the same to 15 significant figures, presumably there is a point in the calculation that can go one of two ways and on some systems it goes the way that makes the test pass and on others it goes the way that makes the test fail.

@valeriy42 please can you look into this as it's a feature importance test so it's most likely your commit related to feature importance that changed this.

**Comment by valeriy42** [comment]
Thank you for describing the issue @droberts195 . I'll take a look.

**Comment by droberts195** [comment]
The changes of #1710/#1711 didn't fix this unfortunately.

@tveasey could one of your changes from 21st have changed the result of this test?

Shall we just put the tolerance up from 8% to 9%?

**Comment by tveasey** [comment]
No I won't didn't change anything in this area. It's interesting it is still failing more consistently, but equally it seems like there is a longer standing issue. I'd say let's increase the tolerance and have an issue to investigate why this is varying from run to run and what caused the recent change.

**Comment by droberts195** [comment]
> why this is varying from run to run

Since 21st it’s not run to run, but _every_ time on the macOS VMs on the London office Mac Minis. The things that might make them different to our laptops are that they only have 3GB RAM, and are running under VMware Fusion. I’m not sure why either of those things would cause a difference. The master branch VM is running a newer compiler version, and is on a newer Mac Mini (hence newer underlying CPU) than the 7.x VM. So it’s a bit strange that they both get exactly the same answer, which is different to our laptops. 🤔
