### ISSUE TITLE
[ML] Higher weighting for tokens at the beginning of messages during categorization

### ISSUE THREAD

**Issue by droberts195** [elastic/ml-cpp#1724]
Many years ago we considered the idea of giving tokens near the beginning of messages higher weightings in categorization.  We rejected the idea, as we had a few data sets at the time that we got worse results for by doing this.

However, more recently we have seen data sets where giving higher weighting to tokens near the beginning of messages would give much better results.  Potentially the weight should taper to zero after a large number of tokens, so that subsequent tokens play no part whatsoever in categorization.

Some research is needed to see what weighting and tapering strategy would work best.  We don't want to change our categorization results _too_ dramatically from what they are today.

Also, for BWC this functionality would need to be enabled by an option that would default to false for jobs created in prior versions.

An example of a message that doesn't categorize well with no additional weighting for early tokens is:

```
a client request body is buffered to a temporary file /tmp/client-body/0000021894, client: 10.8.0.12, server: apm.35.205.226.121.ip.es.io, request: "POST /intake/v2/events HTTP/1.1", host: "apm.35.205.226.121.ip.es.io"
10.8.0.12 - - [29/Nov/2020:21:34:55 +0000] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "elasticapm-dotnet/1.5.1 System.Net.Http/4.6.28208.02 .NET_Core/2.2.8" 27821 0.002 [default-apm-apm-server-8200] [] 10.8.1.19:8200 0 0.001 202 f961c776ff732f5c8337530aa22c7216
10.8.0.14 - - [29/Nov/2020:21:34:56 +0000] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "elasticapm-python/5.10.0" 3594 0.002 [default-apm-apm-server-8200] [] 10.8.1.18:8200 0 0.001 202 61feb8fb9232b1ebe54b588b95771ce4
10.8.4.90 - - [29/Nov/2020:21:34:56 +0000] "OPTIONS /intake/v2/rum/events HTTP/2.0" 200 0 "http://opbeans-frontend:3000/dashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.3.1 Chrome/61.0.3163.100 Electron/2.0.18 Safari/537.36" 292 0.001 [default-apm-apm-server-8200] [] 10.8.1.19:8200 0 0.000 200 5fbe8cd4d217b932def1c17ed381c66b
10.8.4.90 - - [29/Nov/2020:21:34:56 +0000] "POST /intake/v2/rum/events HTTP/2.0" 202 0 "http://opbeans-frontend:3000/dashboard" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/3.3.1 Chrome/61.0.3163.100 Electron/2.0.18 Safari/537.36" 3004 0.001 [default-apm-apm-server-8200] [] 10.8.1.18:8200 0 0.001 202 4735f571928595744ac6a9545c3ecdf5
10.8.0.11 - - [29/Nov/2020:21:34:56 +0000] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "elasticapm-node/3.8.0 elastic-apm-http-client/9.4.2 node/12.20.0" 4913 10.006 [default-apm-apm-server-8200] [] 10.8.1.18:8200 0 0.002 202 1eac41789ea9a60a8be4e476c54cbbc9
10.8.0.14 - - [29/Nov/2020:21:34:57 +0000] "POST /intake/v2/events HTTP/1.1" 202 0 "-" "elasticapm-python/5.10.0" 1025 0.001 [default-apm-apm-server-8200] [] 10.8.1.18:8200 0 0.001 202 d27088936cadd3b8804b68998a5f94fa
```

You can see that the category would ideally be defined by `a client request body is buffered to a temporary file`.  However, without weighting these early tokens higher than the later ones, the chunk of access log that is appended to the message makes the categorizer create many categories, eventually exhausting available memory.

Even something really simple like the strategy below would probably help in cases like the above without radically changing our current results for less bizarre message formats:

* x2 current weighting for the first 10 tokens
* x1 current weighting for the next 30 tokens
* x0 current weighting for subsequent tokens

**Comment by edsavage** [comment]
The positional token weighting scheme will be exposed in the analysis config. The proposed JSON format for the default weighting scheme is:

```
{
positional_weights: [
	{“gte”: 15,
	 “weight”: 0},
	{“gte”: 10,
	 “lt”: 15,
	 “weight”: 2},
	{“lt”: 10,
	 “weight”: 3}
]}
```
This echoes the existing ES range queries so should be reasonably recognisable/understandable while lending itself to basic validation.

**Comment by droberts195** [comment]
The combination of #1903 and elastic/elasticsearch#72805 should be enough to resolve this.

**Comment by droberts195** [comment]
In the end we didn't do what it says in the original issue description.  Higher weighting for tokens at the beginning of messages caused as many problems as it solved.

Instead, the changes we made were:

1. Tokenization preserves email addresses, URLs and file system paths as single tokens
2. We only consider the first non-blank line of each message for categorization
3. We give higher weighting to dictionary words that are adjacent to other dictionary words
