### ISSUE TITLE
[ML][PYTORCH] Investigate PyTorch Threading model

### ISSUE THREAD

**Issue by davidkyle** [elastic/ml-cpp#1815]
LibTorch has to [2 methods](https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html) to control the number of threads used:

```
at::set_num_interop_threads, at::get_num_interop_threads
at::set_num_threads, at::get_num_threads
```

The default value for both is the number of CPU cores.

ML should be a good citizen in terms of consuming resource and the default values may be sub-optimal given the execution profile of an ML node where resource is shared with a JVM.

Investigate multi-threading usage in the inference use-cases and consider the following options:
- Expose a configuration parameter 
- Set the number of threads by a heuristic based on observed performance
- Use the default value

**Comment by droberts195** [comment]
> default values may be sub-optimal given the execution profile of an ML node where resource is shared with a JVM

And also may be shared with other ML processes running on the same node.

**Comment by joshdevins** [comment]
Some notes from our call, some of my initial thoughts...

 * I think this is a tradeoff about optimizing latency (single inference call returning ASAP) or throughput (as many inferences in parallel at a time)
 * For ingest, it's likely that latency is less of a concern vs throughput
 * For reranking, it's likely that overall latency is the primary concern but per-inference latency is not
 * For one-off inference like query understanding, latency is the primary concern
 * Given we care mostly about ingest right now, and some reranking tasks later, I would choose to make this configurable, but default to 1 thread per inference process
 * Foremost should be that this is a good default for most use-cases, second is that it's easy to reason about how to scale inference throughput
 * I think we'll get to the lower latency cases later only
 * I think we'll also get to bulk/batching scenarios only much later as most inference use-cases are not batching

**Comment by joshdevins** [comment]
Summary of conversations so far (I think).
* Simplest, most flexible and highest amount of control would be to have a single process using a single core
* Most memory efficient would be for a single process to use multiple cores since we don't need to have a 1:1 "model in memory" vs cores
* Benchmarking needed to understand throughput and latency characteristics

Feel free to edit this summary :D

**Comment by davidkyle** [comment]
Using the benchmark script from #1948 I evaluated the affect of the varying the number of threads with 2 different models/tasks

1. Bert Large Cased fine tuned conll03 for NER: https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english
2. DistilBERT base uncased fine tuned for SST for Sentiment Analysis: https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english

The benchmarking script took the average of a number or runs for different values of `at::set_num_threads`.

`at::set_num_interop_threads` was fixed at `1`. 

## Results
For both models there is a noticeable elbow point at 2 threads and after 4 threads the performance does not improve significantly. 

![time-vs-numThreads](https://user-images.githubusercontent.com/2353640/127293293-089a05b9-c1fb-4c12-a3a2-b2a25435a059.png)


| Num Threads  | NER Task Time (ms) | SA Task Time (ms) |
|---------------|---------------------|--------------------|
| 1 | 113.124 | 18.064 |
|2|60.674|9.766|
|3|55.77|8.538|
|4|39.882|6.444|
|5|38.418|6.73|
|6|28.376|5.216|
|7|37.166|6.146|
|8|29.44|4.4|
|9|41.112|6.268|
|10|36.718|5.55|
|11|32.068|5.384|
|12|34.166|6.162|
|13|26.654|4.882|
|14|33.458|4.88|
|15|38.642|6.048|
|16|38.478|4.822|
