### ISSUE TITLE
[ML] Support data chunking of CDataSummarizationJsonSerializer

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#1849]
At the moment we only support compressed best forest and data summarization documents without chunking. This functionality has to be extended to support chunking as well.

However, this issue is not a blocker and can be dealt with when we are ready to exchange data with java side.

https://github.com/valeriy42/ml-cpp/blob/270b7aa6ba852f88dee80a16afac557876be0a86/include/api/CDataSummarizationJsonSerializer.h#L28-L28

**Comment by tveasey** [comment]
We are in the position where we write large state documents out chunked, but only expect a single chunk when reading them back in. This means we will currently fail to handle large models which bumps the priority of fixing this issue.
