### ISSUE TITLE
[ML][PyTorch] Missing libnsl.so.1 on CentOS 8

### ISSUE THREAD

**Issue by davidkyle** [elastic/ml-cpp#1933]
The `pytorch_inference` app links to libnsl for the network to host order functions (ntohl) but libnsl is no longer included by default on CentOS 8 and [RHEL 8](https://www.ibm.com/docs/en/cloud-app-management/2019.4.0?topic=systems-preinstallation-linux)

**Comment by droberts195** [comment]
> links to libnsl for the network to host order functions (ntohl)

On Linux `ntohl` is a macro.  It's accidental that we're linking `libnsl.so` really.  On Windows `WS2_32.dll` is needed for `ntohl`, and that was listed in `NETLIBS`, so `NETLIBS` was added to the link line not thinking that what it added for other platforms might no longer be part of those operating systems.
