### ISSUE TITLE
[ML] Gradle fails Elasticsearch tests when run with the ml-cpp side-loaded

### ISSUE THREAD

**Issue by davidkyle** [elastic/ml-cpp#1963]
When using the `elasticsearch-extra` trick to run against a local build of `ml-cpp` (i.e. create the `elasticsearch-extra` directory as a sibling of the `elasticsearch` repo and softlink `ml-cpp` inside it) the integration tests in the Elasticsearch repo fail even if the individual tests pass. The error is:

```
FAILURE: Build failed with an exception.

* What went wrong:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 23s
```

Elasticsearch is currently on Gradle version 7.1.1 while this repo is using Gradle 6.8.3, perhaps upgrading would do the trick?

## Reproduce
Set up the elasticsearch-extra repo and run a test, any test will do it.
```
 ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.nlp.BertRequestBuilderTests.testBuildRequest"
```

**Comment by davidkyle** [comment]
> perhaps upgrading would do the trick?
 
No updating `gradle-wrapper.properties` to be the same as the in the Elasticsearch repo did not work. 

While upgrading I got this error

```
> Configure project :buildSrc
The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's shutdown in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.1.1/userguide/upgrading_version_6.html#jcenter_deprecation
        at build_9wlfif6ooejmas8bcbgtnbwqi$_run_closure1.doCall(/Users/davidkyle/source/ml-cpp/buildSrc/build.gradle:8)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

So the deprecation must be tackled.

**Comment by droberts195** [comment]
The `jCenter()` problem is trivial to fix.  (We already have `mavenCentral()` listed too, so just need to delete one line of code.)

Unfortunately another deprecation looks more tricky:

```
Subproject ':ml-cpp' has location '/Users/dave/elasticsearch-extra/ml-cpp' which is outside of the project root. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. Consult the upgrading guide for further information: https://docs.gradle.org/7.1.1/userguide/upgrading_version_7.html#deprecated_flat_project_structure
```

It seems like the whole idea of having `elasticsearch-extra` parallel to `elasticsearch` is no longer viable.  Maybe `elasticsearch-extra` now needs to be a sub-directory of `elasticsearch` instead of parallel to it.  What do you think @mark-vieira?

**Comment by droberts195** [comment]
@davidkyle to allow your debugging to continue while this is resolved I suggest just adding `-Porg.gradle.warning.mode=none` to your local `gradlew` command line for the time being.

**Comment by mark-vieira** [comment]
I was under the impression this mechanism was implemented as a composite build but it's not, instead we seem to be _adding_ a subproject to the Elasticsearch project. I'm not _completely_ certain this would eliminate the deprecation enforcement issue (perhaps we can override in the included build) but it would alleviate the _specific_ complaint above.

For now overriding the deprecation warning mode setting as David suggests should get you by. I'll investigate refactoring this capability to use the appropriate Gradle features.

**Comment by davidkyle** [comment]
I seem to be stuck on Gradle 7.1.1 after experimenting with the upgrade. For 7.1.1 the correct command line flag is `--warning-mode=none`

Is it worth taking `gradlew` 7.1.1 for parity with elasticsearch anyway? 
It _seems_ to be working on my on my machine :shipit:

**Comment by mark-vieira** [comment]
> Is it worth taking gradlew to 7.1.1 for parity with elasticsearch anyway? It seems to be working on my on my machine 

If it doesn't otherwise cause issues, yeah, that's probably a good idea.

**Comment by droberts195** [comment]
Another thing Gradle have deprecated is the `-b` option to specify an alternative build file.  We use this with `upload.gradle` to separate out the code that combines the builds from all the platforms into a single zip file from the main build.

**Comment by mark-vieira** [comment]
> Another thing Gradle have deprecated is the -b option to specify an alternative build file. We use this with upload.gradle to separate out the code that combines the builds from all the platforms into a single zip file from the main build.

For what it's worth you can still keep these things separate, just to reduce the size of the root `build.gradle` file and simply _apply_ the `upload.gradle` [as a script plugin](https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins).

**Comment by davidkyle** [comment]
The solution now is to call gradle from the elastcisearch repo with the ` --include-build` pointing to the ml-cpp repo. 

The example in the issue description now becomes 

`
 ./gradlew ':x-pack:plugin:ml:test' --tests "org.elasticsearch.xpack.ml.inference.nlp.BertRequestBuilderTests.testBuildRequest"  --include-build /path/to/ml-cpp
`
