### ISSUE TITLE
[ML] Unit tests do not assert the skip sampling behaviour for metric models

### ISSUE THREAD

**Issue by davidkyle** [elastic/ml-cpp#2043]
The unit tests test the effect of skip sampling with a detection rule by creating 2 identical models but one of which has a detection rule set. The same data is put in both models, then the model with the rule has extra data inserted which should be ignored due to the detection rule.  The tests then assert that the 2 models are the same- and therefore that they saw the same data and skip sampling worked- by comparing checksums. This works very well for event rate models but fails for metric models as the checksums will always be different because the decay rate and prior change. It is not possible to test the effect of skip sampling in isolation. 

`CMetricPopulationModelTest::testIgnoreSamplingGivenDetectionRules` fails the checksum tests because the trend does not always have the `lastValueTime`.

The problematic tests are

- `CMetricPopulationModelTest::testIgnoreSamplingGivenDetectionRules`
- `CMetricModelTest::testIgnoreSamplingGivenDetectionRules`

**Comment by droberts195** [comment]
These tests have been rewritten in #2053
