### ISSUE TITLE
4 test case failures observed on Intel

### ISSUE THREAD

**Issue by chakravarthy392** [elastic/ml-cpp#220]
Got the below failures on Intel while executing the ml-cpp v6.4.1 test suit. Please let me know if the below mentioned steps I have followed or correct or not.

!!!FAILURES!!!
Test Results:
Run:  248   Failures: 4   Errors: 0

1) test: CTimeUtilsTest::testToIso8601 (F) line: 64 CTimeUtilsTest.cc
equality assertion failed
- Expected: 2008-04-11T15:53:44+0100
- Actual  : 2008-04-11T14:53:44+0000

2) test: CTimeUtilsTest::testToLocal (F) line: 95 CTimeUtilsTest.cc
equality assertion failed
- Expected: Fri Apr 11 15:53:44 2008
- Actual  : Fri Apr 11 14:53:44 2008

3) test: CTimeUtilsTest::testStrptime (F) line: 196 CTimeUtilsTest.cc
equality assertion failed
- Expected: 1245774295
- Actual  : 1245777895

4) test: CTimeUtilsTest::testTimezone (F) line: 350 CTimeUtilsTest.cc
equality assertion failed
- Expected: 1227728437
- Actual  : 1227710437

ml -cpp Version : v 6.4.1
Java : AdoptOpenJDK 10 - hotspot

Steps to reproduce:
1. set the environment as mentioned in https://github.com/elastic/ml-cpp
2.git clone https://github.com/elastic/ml-cpp.git
3.git checkout v6.4.1
4.cd /home/test/ml-cpp
5.  ./gradlew assemble 2>&1| tee -a 641Build.log
6.  ./gradlew test --continue -Dtests.haltonfailure=false -Dtests.timeoutSuite=5000000!

Full log of test execution:
[X86_results.txt](https://github.com/elastic/ml-cpp/files/2427689/X86_results.txt)

**Comment by droberts195** [comment]
I suspect that the calls in the tests that set the timezone, for example `ml::core::CTimezone::setTimezone("Europe/London")`, are not working for some reason.

Which Linux distribution are you using?

Do you have the `tzdata` package installed on your machine?  That would give you files like `/usr/share/zoneinfo/Europe/London`.

If it's not that, please can you let me know your environment variables that might be affecting this.  `env | egrep '^TZ|^LC|^LANG'` should get them.

And finally, if you just want to make progress without digging into this, delete the line `runner.addTest(CTimeUtilsTest::suite());` from your local copy of `lib/core/unittest/Main.cc` - we don't actually do timestamp parsing in the production code needed to run an ML job in the Elastic stack, so it's not critical that this functionality works.

**Comment by chakravarthy392** [comment]
@droberts195 
distribution : ub 16.04
uname -a : Linux f0c7d29e2b37 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
`tzdata` is not installed and did not get any result for `env | egrep '^TZ|^LC|^LANG'.

Thanks for mentioning that these failures are not critical.

**Comment by droberts195** [comment]
OK, in that case I suspect that `apt-get install tzdata` will solve this problem.

I'll add a note to the Linux setup instructions to say that this package is necessary for development.

I think we didn't notice this before because the default install of most Linux distributions will include the timezone database.

**Comment by chakravarthy392** [comment]
yes @droberts195 , it solved the issue,Thanks.
