### ISSUE TITLE
[ML] Fix flaky CBoostedTreeTest/testMseIncrementalAddNewTrees and re-enabled it

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#2271]
```
// TODO Fix flacky test and re-enabled
```

https://github.com/valeriy42/ml-cpp/blob/79a909f112d75f9943e88aeb56fa8dfabb6f3a75/lib/maths/analytics/unittest/CBoostedTreeTest.cc#L1446

**Comment by droberts195** [comment]
Fixed by #2296
