### ISSUE TITLE
[ML] Fatal error during DFA run

### ISSUE THREAD

**Issue by pheyos** [elastic/ml-cpp#2362]
After #2298 went in, we noticed some (occasional) Kibana test failures during DFA cloning, with this ES error in the logs:
```
[o.e.x.m.p.AbstractNativeProcess] [ftr] [bm_1_1655479347664_clone] analytics/3234 process stopped unexpectedly: Fatal error: 'terminate called after throwing an instance of 'std::length_error'', version: 8.4.0-SNAPSHOT (build 4a827ea6fdf104)
      Fatal error: '  what():  vector::reserve', version: 8.4.0-SNAPSHOT (build 4a827ea6fdf104)
      Fatal error: 'si_signo 11, si_code: 128, si_errno: 0, address: 0x7f328c002941, library: /lib/x86_64-linux-gnu/libc.so.6, base: 0x7f328bfe0000, normalized address: 0x22941', version: 8.4.0-SNAPSHOT (build 4a827ea6fdf104)
```

**Comment by droberts195** [comment]
It means something that was changed in #2298 is causing us to make a `vector<T>::reserve(n)` call when `n * sizeof(T)` is greater than or equal to 2^64.  Since this would be a huge number, most likely there is somewhere where `n` is found by casting a small negative number to `std::size_t`.

**Comment by pheyos** [comment]
Corresponding Kibana test failure issue: https://github.com/elastic/kibana/issues/134430

**Comment by droberts195** [comment]
The Kibana failure hasn't been seen again since reenabling the test - closing.
