### ISSUE TITLE
[ML] Annotate first occurrence of rare categories

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#2443]
As an extension to explaining anomaly scores for `rare` detectors, annotate when the category was seen for the first time.

**Comment by valeriy42** [comment]
Adding functionality seems to be as simple as 
```C++
CEventRateModel::computeProbability() {
//...
resultBulder.anomalyScoreExplanation(pJoint.anomalyScoreExplanation());
//...
bool everSeenBefore = this->firstBucketTimes()[pid] != startTime;
resultBuilder.anomalyScoreExplanation().everSeenBefore(everSeenBefore);
```

**Comment by tveasey** [comment]
This looks right to me (note there may be some issue with alignment of time in the bucket, but modulo that detail this should work). This is probably the most important additional information to add to rare results.

One thing where I don't think we do a good job is to clearly explain how we're measuring rare. An option for this would to be to say something like occurs in `1 out of every <n> buckets` for `rare by x` and `is seen for 1 in every <n> values of <y>` for `rare by x over y`. This information can be extracted from the concentrations of the Dirichlet distribution.

**Comment by valeriy42** [comment]
In `CAnnotatedProbability`, we have an enum `EDescriptiveData` and `SAnnotatedProbability::s_DescriptiveData` that partially contain the information we want to surface for the explanation of the anomaly score. Since `s_DescriptiveData` is never copied and passed to `CJsonOutputWriter`, I will delete the obsolete code as a part of the implementation. 

Furthermore, by comparing the probability concentration of the rare category to the concentration of the median in `m_ProbabilityPrior`, I can write something like "Category X occurs N times less frequently than the typical (median) category."  I can use `ProbabilityCache` to compute the median concentration once and reuse it for the same bucket.

The code should be updated in bot `EventRate` and `EventRatePopulation`:
-  "Rate by X" -> `EventRate`
- "Rate over Y" -> `EventRatePopulation`
