### ISSUE TITLE
[ML] Add IPEX library to the docker container

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#2558]
Ensure that the PyTorch models quantized using the [IPEX library](https://github.com/intel/intel-extension-for-pytorch) can be executed in the Docker container on Linux.

This requires the IPEX library to be linked with the PyTorch library of the corresponding version.

The build scripts (CMake files and DOCKERFILE) need to be extended to support IPEX quantized models on Linux.

**Comment by droberts195** [comment]
As well as the Docker container, please update the build instructions in [here](https://github.com/elastic/ml-cpp/blob/main/build-setup/linux.md) so we keep everything in sync. And also the [script that copies 3rd party dependencies into our distribution](https://github.com/elastic/ml-cpp/blob/main/3rd_party/3rd_party.cmake) and the [3rd party license information](https://github.com/elastic/ml-cpp/tree/main/3rd_party/licenses) will need updating.

**Comment by valeriy42** [comment]
Building `ml-cpp` inside the CentOS:7 Docker container fails as IPEX library is missing symbols available in glibc>=2.27, while the latest glibc version for CentOS:7 is [2.17](https://centos.pkgs.org/7/centos-x86_64/glibc-2.17-317.el7.x86_64.rpm.html). 

- I tried to build a new glibc, but it didn't work with gcc build against an older version of glibc.
- I tried to bootstrap the compiler: install older gcc, build new glibc, build new gcc, but it didn't work either. It returned error similar to:
```
/usr/bin/bash: relocation error: /usr/local/glibc-2.38/lib/libc.so.6: symbol _dl_audit_preinit, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```
- I was able to migrate our Dockerfile to use Rocky Linux 9 (RHEL 9) as the base image.

**Comment by droberts195** [comment]
We cannot use a newer version of glibc. We have to run on all the distributions listed in the Elasticsearch [support matrix](https://www.elastic.co/support/matrix), and that includes RHEL/CentOS 7. So we need to run on glibc 2.17.

The only solution I can see is to build our own build of IPEX, like we build most of our other dependencies, inside our CentOS 7 build image. It looks like the build process is probably similar to PyTorch itself, using a [`setup.py` script](https://github.com/intel/intel-extension-for-pytorch/blob/release/1.13/setup.py). The project is Apache 2 licensed, so there's no legal issue prohibiting us from doing our own build. It's just a question of working out which options to use. It looks like we should do the build while MKL is available in the build image, and use the same MKL we're using for PyTorch, specified using the [`MKLROOT` option](https://github.com/intel/intel-extension-for-pytorch/blob/013d8f4cb5217fe54a41a77cc7d9ccd8b250cb9b/setup.py#L25).

**Comment by droberts195** [comment]
Added in #2547
