### ISSUE TITLE
[ML] data_frame_analyzer crashes when it receives no data

### ISSUE THREAD

**Issue by dimitris-athanasiou** [elastic/ml-cpp#511]
If the process receives the end-of-data message without having received any data, it crashes. We should close the process gracefully when this happens.

**Comment by tveasey** [comment]
I can't reproduce this. Also, valgrind shows up no issues. Is it the case that you are running with a config with zero rows? We do validate this and exit with a non-zero return value in this case, but that is intentional.

**Comment by tveasey** [comment]
This was fixed in#585.
