### ISSUE TITLE
[ML] Nginx remote_ip_url_count results regression

### ISSUE THREAD

**Issue by sophiec20** [elastic/ml-cpp#57]
Forst noticed in: `{
  "build" : {
    "hash" : "a47564f",
    "date" : "2018-04-09T21:45:51.347364Z"
  },
`

The ML Module Nginx jobs in 6.3 are producing significantly different results to those found in 6.0. Job config:
```
high_dc(nginx.access.url) over nginx.access.remote_ip
bucket_span=1h
incluencer=nginx.access.remote_ip
```

6.0.1 Overall score
![image](https://user-images.githubusercontent.com/4185750/38807171-ad8fe75a-4173-11e8-8295-7102dfe0cdb0.png)

6.3.0 Overall score
![image](https://user-images.githubusercontent.com/4185750/38807161-a01f01b4-4173-11e8-9927-b4e493a355bf.png)

The 6.0.1 top influencer is `72.57.0.53` on `2017-02-23`. This is not in the top 10 list for 6.3.0.

The top 10 influencer lists only share 2 remote_ips: `196.89.216.188` and `154.187.183.122`

A very notable difference is for `95.142.104.2`...
  
 `95.142.104.2` 6.0.1
![image](https://user-images.githubusercontent.com/4185750/38807635-2aae400a-4175-11e8-8e53-e91eed399f06.png)

 `95.142.104.2` 6.3.0
![image](https://user-images.githubusercontent.com/4185750/38807663-3d536e88-4175-11e8-905e-52afda362ad2.png)

Is this an intended or unintended consequence of recent improvements?

**Comment by tveasey** [comment]
The latest behaviour is broadly similar to 6.0.1:
<img width="1665" alt="Screenshot 2020-12-08 at 20 31 55" src="https://user-images.githubusercontent.com/7591487/101538101-8688fe00-3994-11eb-9572-1748358653b5.png">
I think there is a case for always selecting a model using population analysis, but this is a significant change which we would need to assess across our full regression suite.
