### ISSUE TITLE
[ML] Improve modeling of periodic, sparse data

### ISSUE THREAD

**Issue by richcollier** [elastic/ml-cpp#696]
Prospective customer use case has once-daily sampled data of a program executed at a certain time. 

![image](https://user-images.githubusercontent.com/7461287/65623546-114f2a00-df96-11e9-9442-2191794b0518.png)

Tried to model with 4h bucket span in order to get somewhat timely alerting if a gap exists (a monitored program does not run), but the modeling isn't adequate. Anomalies are not raised at the time of the gap of execution:

![image](https://user-images.githubusercontent.com/7461287/65623403-b61d3780-df95-11e9-892c-bc5d1938e2fb.png)

The modeling and the anomaly results are better with a 1d bucket_span:

![image](https://user-images.githubusercontent.com/7461287/65623733-73a82a80-df96-11e9-950e-612a9b1e2174.png)

But, the downside is an increased "delay to alert" in this case.

**Comment by tveasey** [comment]
I spent a little time investigating this. The issue with detecting the missing samples with the count function at short bucket lengths comes down to our handling of sparse signals: signals where most buckets are empty. We smoothly transition to modelling counts in only non-empty buckets as fewer buckets are populated, but this interferes with our ability to detect the periodic nature of the buckets which are non-empty. This seems like a blindspot in our modelling capabilities it would be good to address.

In the meantime a possible work around would be to pre-aggregate data to get the counts and then analyse this metric with the sum function. This should mean we explicitly pass zeros for empty buckets and so every bucket will be populated.

**Comment by richcollier** [comment]
Pre-aggregating the counts does not seem possible because the date_histogram agg cannot fill in artificial values when there are no docs in that interval.

I've noticed that a 6h bucket_span for the job actually performs quite well:

![image](https://user-images.githubusercontent.com/7461287/65733773-113a5180-e09e-11e9-9171-0100c5144e90.png)

And while it isn't quite as timely as the original requirement of 4h, it is much more timely than 1d.

**Comment by tveasey** [comment]
I'll keep this issue open since it would be good to address the first part of (this)[https://github.com/elastic/ml-cpp/issues/696#issuecomment-535435042] comment.

**Comment by tveasey** [comment]
I've been experimenting with some different options. I have an option which works well on this data set and so far looks promising on a variety of different sparse data sets.

![Screenshot 2019-10-07 at 18 21 16](https://user-images.githubusercontent.com/7591487/66333792-9db30280-e92f-11e9-9d04-a3129d32bd8b.png)

This needs a bit more testing, but I'm optimistic it should be available for 7.5.
