### ISSUE TITLE
[README] Apple Developer tools link in mac os env setup is broken 

### ISSUE THREAD

**Issue by Winterflower** [elastic/ml-cpp#813]
The macos.md build setup instruction mention this link https://developer.apple.com/technologies/xcode.html, which appears to lead to a Page Not Found.
https://github.com/elastic/ml-cpp/tree/master/build-setup

**Comment by edsavage** [comment]
I'll expand this PR a little to include:

* Details of where to get Xcode from/which version (fix in build-setup/macos.md)
* How to build (add to README.md)
  * how to build a binary of say autodetect or data_frame_analyzer 
  * Where to find it once the build process finishes. make isn't super widely used in the more high-level lang world, so it can be a bit tricky at first
