### ISSUE TITLE
[ML] Weekend periodicity lost in first week after reopening anomaly detection job

### ISSUE THREAD

**Issue by dolaru** [elastic/ml-cpp#820]
Reproduced in 6.8.4 with the `event_rate_gen` dataset

The job was run on 5 weeks of data (2015-01-05 -> 2015-02-09), and weekend periodicity has been established. After restarting the job and the rest of the dataset has been processed, it can be noticed that the first week processed after reopening has lost weekend periodicity.
![image](https://user-images.githubusercontent.com/1785030/68671078-647d3c00-0546-11ea-9f20-006ca5de965e.png)

## Steps to reproduce
1. Create a job with model plot enabled
2. Run a datafeed on the first 5 weeks of the data, and let it gracefully close
3. Check that the model plot shows that weekend periodicity is being modelled
4. Restart the datafeed for the remainder of the dataset
5. Notice that the first week processed after reopening the job has lost the weekend periodicity

**Comment by wwang500** [comment]
Verified it on 6.8.5 BC1, and confirm it is fixed.
