### ISSUE TITLE
Outlier memory usage code adds negative of unsigned number

### ISSUE THREAD

**Issue by droberts195** [elastic/ml-cpp#836]
Visual C++ is issuing this warning:

```
COutliers.cc(931,40): warning C4146: unary minus operator applied to unsigned type, result still unsigned
        recordMemoryUsage(-pointsMemory);
```

The compiler is correct that the value will wrap.  `pointsMemory` is unsigned and `recordMemoryUsage` is a function that takes an unsigned argument.  Therefore the unary minus operator is going to result in a huge number being passed to the function, not a negative number as desired.

However, it probably works as desired because the net effect of adding `pointsMemory` followed by `-pointsMemory` will be to add a total of 2^64 to a 64 bit unsigned number, which will wrap it back to where it started.

This incredibly subtle behaviour is not commented though.  It would be very easy for somebody to assume adding negative numbers to the memory usage works as expected.  I think ideally the way the memory is reduced should be refactored to use subtraction rather than wrapping, and if that's hard then at least the offending code should be commented to explain how it works and why careful thought is required before copying the approach elsewhere.

**Comment by tveasey** [comment]
This is almost certainly unintentional, we should be using `std::int64_t` for the argument type of `recordMemoryUsage` since we won't possibly overflow this.
