### ISSUE TITLE
[ML] Trees can have leaves without any data points

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#849]
It seams that the splitting algorithm continues to split a node even if there are no data points in one of the branches. This leads to creation of degenerated large trees, which are only limited by the maximum tree size. This also breaks algorithms like TreeSHAP, which assume that every leaf contains some data.

**Comment by valeriy42** [comment]
IMO the solution should introduce a `min_samples_split` and `min_samples_leaf` parameters similar to [how sklearn does this](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html). This doesn't have to be a hyperparameter, but can be specified by user if need be. Having default values 2 for split and 1 for leaf would be enough.

**Comment by tveasey** [comment]
This is pretty weird. We definitely shouldn't split if the gain is zero and the gain would definitely be no larger than zero if either leaf is empty. This implies a bug to me. I'm not against a minimum leaf count as well, but we should understand the origin of the current behaviour.

**Comment by valeriy42** [comment]
I think, this was related to #851, the tree depth hyperparameter overrides didn't set the actual parameters, this resulted in gain being nan (another check we should make), and so the algorithm continued to split.
