### ISSUE TITLE
[ML] Add unit test checks for new hyperparameters in supervised learning

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#851]
For the tests with all hyperparameters set (e.g. `m_RegularizationOverride.*`), we need to check that those would set the actual hyperparameter values (e.g. `m_Regularization.*`). I just noticed that setting `softTreeDepthLimit` and `softTreeDepthTolerance` was missing and the unit test  `testRunBoostedTreeRegressionTrainingWithParams` didn't fail.

**Comment by tveasey** [comment]
Good catch!
