### ISSUE TITLE
[ML] Instrument Data Frame Analysis Job to report state information to Java backend

### ISSUE THREAD

**Issue by valeriy42** [elastic/ml-cpp#899]
In order to provide users more informative insights into the current job state, we should establish a communication from the running data frame analysis job to the Java back-end that goes beyond the simple progress indicator. This information should be provided on iteration-by-iteration basis.

As discussed in the team, we should start with providing information about 
+ complete set of analysis parameters (inclusive inferred once)
+ peak memory usage
+ intermediate quality of results

**Comment by valeriy42** [comment]
In order to consolidate different kind of statistics that we want to communication across different kind of data frame analysis jobs, I suggest to introduce a new class `CDataFrameAnalysisState` and move the callback functions `memoryUsageCallback` and `recordProgressCallback` as members to this class. Additionally I would define 
+ `updateQualityOfResults()`, 
+  `updateParameters()`
+ `writeState(core::CRapidJsonConcurrentLineWriter& writer)`

 Hence the class takes care of keeping the state of the job (with sub-classes for outlier detection and supervised learning) and how to serialize itself into a set of different JSON objects and write them into the pipe.

WDYT @tveasey ?

**Comment by tveasey** [comment]
This sounds very sensible to me :)

**Comment by valeriy42** [comment]
Is duplicate of #976
